# SwiftLint Configuration for Killshot iOS App
# This file configures SwiftLint rules for consistent Swift code formatting

# Disabled rules - rules we don't want to enforce
disabled_rules:
  - trailing_whitespace  # We'll let Prettier handle this
  - line_length          # We'll set custom limits below

# Opt-in rules - additional rules we want to enable
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicit_return
  - operator_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_type_annotation
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - xct_specific_matcher
  - yoda_condition

# Files to include in linting
included:
  - Killshot

# Files to exclude from linting
excluded:
  - KillshotTests
  - KillshotUITests
  - Pods
  - .build
  - DerivedData

# Custom rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

function_parameter_count:
  warning: 5
  error: 8

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - url
    - urlRequest
    - urlSession

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# Custom rules for SwiftUI
custom_rules:
  # Enforce MARK comments for better organization
  mark_comment_style:
    name: "MARK Comment Style"
    regex: '^// MARK: - .+$'
    message: "MARK comments should follow the format: // MARK: - Description"
    severity: warning

  # Enforce documentation comments for public APIs
  public_api_documentation:
    name: "Public API Documentation"
    regex: '^(public|open) (class|struct|enum|protocol|func|var|let).*$'
    message: "Public APIs should have documentation comments"
    severity: warning
    match_kinds:
      - comment
      - doccomment

# Reporter configuration
reporter: "xcode"

# Analyzer rules (requires SwiftLint 0.50+)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import
  - unused_private_declaration
